services:
  leetcode-postgres:
    container_name: leetcode-postgres
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: leetcode
  leetcode-redis:
    container_name: leetcode-redis
    image: redis:7.2.4
    ports:
      - "6379:6379"